# Generated by Django 5.2.14 on 2026-06-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_encryptedtotpdevice_widen_totp_key'),
        ('accounts', '0004_mfaresetrequest'),
    ]

    operations = []