# Generated by Django 5.2.14 on 2026-06-30 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_0004_encryptedtotpdevice_widen_totp_key_0004_mfaresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jit_disclosure_window_minutes', models.IntegerField(default=120, help_text='The JIT disclosure window in minutes. Must be at least 30 minutes.', validators=[django.core.validators.MinValueValidator(30)])),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configuration',
            },
        ),
    ]
