# Generated by Django 5.2.14 on 2026-05-22 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('preferred_language', models.CharField(blank=True, max_length=50)),
                ('accessibility_needs', models.TextField(blank=True)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_seniors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
