# Generated by Django 5.2.14 on 2026-06-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seniors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="senior",
            name="consent_status",
            field=models.CharField(
                choices=[
                    ("not_recorded", "Not Recorded"),
                    ("given", "Given"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="not_recorded",
                max_length=20,
            ),
        ),
    ]
