# Generated by Django 5.2.14 on 2026-07-06 07:43
#
# SR-DATA-05: encrypt Senior PII at rest. The AlterField operations widen the
# columns to TEXT and switch them to EncryptedTextField; the data migration then
# rewrites any existing (plaintext) rows as ciphertext.

import seniors.fields
from django.db import migrations

_PII_FIELDS = ['address', 'phone_number', 'next_of_kin_name', 'next_of_kin_contact']


def encrypt_existing(apps, schema_editor):
    """Encrypt existing plaintext PII by re-saving each row.

    Reads decrypt via EncryptedTextField.from_db_value (legacy plaintext rows
    fail to decrypt and are returned unchanged); the subsequent save() encrypts
    via get_prep_value. Idempotent — already-encrypted rows round-trip cleanly.
    """
    Senior = apps.get_model('seniors', 'Senior')
    for senior in Senior.objects.all().iterator():
        senior.save(update_fields=_PII_FIELDS)


def decrypt_existing(apps, schema_editor):
    """Reverse: rewrite ciphertext back to plaintext via raw SQL.

    ORM writes would re-encrypt (get_prep_value still runs at this migration
    state), so we read the raw ciphertext columns and UPDATE with plaintext
    directly, before the reverse AlterField narrows the columns again.
    """
    from cryptography.fernet import InvalidToken

    from seniors.fields import _fernet

    def to_plain(value):
        if not value:
            return value
        try:
            return _fernet().decrypt(value.encode()).decode()
        except InvalidToken:
            return value

    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT id, address, phone_number, next_of_kin_name, '
            'next_of_kin_contact FROM seniors_senior'
        )
        rows = cursor.fetchall()
        for pk, *values in rows:
            plains = [to_plain(v) for v in values]
            cursor.execute(
                'UPDATE seniors_senior SET address=%s, phone_number=%s, '
                'next_of_kin_name=%s, next_of_kin_contact=%s WHERE id=%s',
                [*plains, pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('seniors', '0002_add_consent_status_to_senior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior',
            name='address',
            field=seniors.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='next_of_kin_contact',
            field=seniors.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='next_of_kin_name',
            field=seniors.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='phone_number',
            field=seniors.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
