# Generated by Django 5.2.14 on 2026-05-22 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seniors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('ended', 'Ended')], default='proposed', max_length=20)),
                ('volunteer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('senior_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_matches', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='seniors.senior')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_volunteer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ended'), _negated=True), fields=('volunteer', 'senior'), name='unique_active_volunteer_senior_match')],
            },
        ),
    ]
