from django.urls import path

from .views import (
    AcceptInviteView,
    ChangePasswordView,
    ContactView,
    LoginView,
    LogoutView,
    MeView,
    MFADisableView,
    MFAResetRequestView,
    MFASetupView,
    MFAStatusView,
    MFAVerifyView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RegisterView,
    ResendVerificationView,
    VolunteerDeactivationRequestView,
    VerifyEmailView,
)

urlpatterns = [
    path('register', RegisterView.as_view(), name='auth-register'),
    path('verify-email', VerifyEmailView.as_view(), name='auth-verify-email'),
    path('resend-verification', ResendVerificationView.as_view(), name='auth-resend-verification'),
    path('accept-invite', AcceptInviteView.as_view(), name='auth-accept-invite'),
    path('contact', ContactView.as_view(), name='auth-contact'),
    path('login', LoginView.as_view(), name='auth-login'),
    path('logout', LogoutView.as_view(), name='auth-logout'),
    path('me', MeView.as_view(), name='auth-me'),
    path('change-password', ChangePasswordView.as_view(), name='auth-change-password'),
    path('deactivation-request', VolunteerDeactivationRequestView.as_view(), name='auth-deactivation-request'),
    path('mfa/setup', MFASetupView.as_view(), name='auth-mfa-setup'),
    path('mfa/verify', MFAVerifyView.as_view(), name='auth-mfa-verify'),
    path('mfa-reset/request', MFAResetRequestView.as_view(), name='auth-mfa-reset-request'),
    path('mfa/status', MFAStatusView.as_view(), name='auth-mfa-status'),
    path('mfa/disable', MFADisableView.as_view(), name='auth-mfa-disable'),
    path('password-reset/request', PasswordResetRequestView.as_view(), name='auth-password-reset-request'),
    path('password-reset/confirm', PasswordResetConfirmView.as_view(), name='auth-password-reset-confirm'),
]
