# Generated by Django 5.2.14 on 2026-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befriending_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='followup_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='followup_outcome',
            field=models.CharField(blank=True, choices=[('senior_well', 'Senior is well'), ('rescheduled', 'Session rescheduled'), ('escalated', 'Welfare concern escalated')], max_length=20),
        ),
    ]
