# Generated by Django 5.2.14 on 2026-06-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
