# Generated by Django 5.2.14 on 2026-06-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_append_only_triggers'),
        ('audit', '0002_auditlogentry_metadata'),
    ]

    operations = []
